using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics; // Добавляем using для Robust.Client.Graphics

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class EscapeMenu : DefaultWindow
    {
        public EscapeMenu()
        {
            RobustXamlLoader.Load(this);

            /* RootPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.FromHex("#0A0A0A").WithAlpha(0.5f)
            }; */
        }
    }
}
