name: YAML Linter Nowhere

on:
  push:
    branches: [ master, staging, stable ]
  merge_group:
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  build:
    name: YAML Linter
    if: github.actor != 'IanComradeBot' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Download parts
        run: |
          git clone "${{ secrets.NOWHERE }}"
          mv Nowhere/_PrivateResources/_PPrototypes Resources/Prototypes/
          mv Nowhere/_PrivateResources/_PTextures Resources/Textures/
          mv Nowhere/_PrivateShared Content.Shared/_PrivateShared
          mv Nowhere/_PrivateServer Content.Server/_PrivateServer
          mv Nowhere/_PrivateClient Content.Client/_PrivateClient
      - name: Setup submodule
        run: |
          git submodule update --init --recursive
      - name: Pull engine updates
        uses: space-wizards/submodule-dependency@v0.1.5
      - name: Update Engine Submodules
        run: |
          cd RobustToolbox/
          git submodule update --init --recursive
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: 9.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:WarningsAsErrors= /m
      - name: Run Linter
        run: dotnet run --project Content.YAMLLinter/Content.YAMLLinter.csproj --no-build
